#cloud-config
groups:
  - foogroup

runcmd:
  - /usr/local/bin/fixNFSMounts
  - mount -a
  - salt-call state.apply configure/sshd
  
salt_minion:
    pkg_name: 'salt-minion'
    service_name: 'salt-minion'
    config_dir: '/etc/salt'
    conf:
        master: salt.cfn.upenn.edu
        hash_type: sha256
        id: bsc-compute-image.pennbrain.upenn.edu
    public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjg/3z9S+mOZBDZj/E+X0
        4U86ol59lJT9HLqPtq9RQE4IUfmat4URr2X1GQxm7q7dZkj5dFgqG/Av63qBPle7
        DdfdF1Dp/CX8yPaMldowAa991Y1rCVZYlKJWN7xPK4brQImxscz3ezfQFiT5cbRe
        NQbjra5Ho8cxhZJi4MTIIWfji1gWMUjCYy++Z/o6owsHFgCz9IDWfl+aPIsiZggm
        dRNo1qzODDtbWxzuqCtYqT2Qu3Ozv7QnnKGJ4VZ7pw7fu4kNpJeK09YrnXKOjKHR
        ZJejzCDNcMpdIC7Jgg48ydzz6TQQ1dRPtc/4k6YkU/yeplZlFrOM4MMhFBfGMgAz
        UwIDAQAB
        -----END PUBLIC KEY-----
    private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAjg/3z9S+mOZBDZj/E+X04U86ol59lJT9HLqPtq9RQE4IUfma
        t4URr2X1GQxm7q7dZkj5dFgqG/Av63qBPle7DdfdF1Dp/CX8yPaMldowAa991Y1r
        CVZYlKJWN7xPK4brQImxscz3ezfQFiT5cbReNQbjra5Ho8cxhZJi4MTIIWfji1gW
        MUjCYy++Z/o6owsHFgCz9IDWfl+aPIsiZggmdRNo1qzODDtbWxzuqCtYqT2Qu3Oz
        v7QnnKGJ4VZ7pw7fu4kNpJeK09YrnXKOjKHRZJejzCDNcMpdIC7Jgg48ydzz6TQQ
        1dRPtc/4k6YkU/yeplZlFrOM4MMhFBfGMgAzUwIDAQABAoIBAFArQrXOYSD4D44U
        4R3hj6f2hihLGqNW0N/9iEyX80pOvvND4MPgHHLXHtHb5dqcY+TtGZlGh7zsdp50
        q6r651yQjPwzdVgON/FQ8VU/pAfPeTuiat0CFUsLsYwSgLsXkHsDOXwVJzQp8wwM
        IZjBKMjT8nh4+YS7TH8MdTBS3H28w6XisLV949CRu7A8JRz3gWxrwUsbo/otwnP5
        5O1xSut+bk14x9Ab5Y08Te+eKVB+S80p2cQw5wHdRoRpvGE4PgpR28YbR7Msv+8s
        VVl2LooihbycxeI8dOvinXe1mwe3BmOKKd01DTInlY7kgW8fLKqwOG8TXtOrijdX
        6X+YoUECgYEAugo43OCKKEyR8mI5c1EgrnpOtwzjZ+UmOQwnLJlq3CBJ9oNcJZ+x
        ILPCRo70KiUAD6I8tKqZ4LFMv0HTS/MG/6tXdTI6OHp8ExxqANEEyUqr4Uavv0WJ
        XNojq2p+qAbwwsCHCMIt0o27ee5sLgV/2H1Bpd7uQD7+FHkdHP4O4sUCgYEAw3wY
        JUSusz1JCxTQ9270mgjcCJjIIflmJW1UHdcXuP5IBabwKFWzHL5EQ1f7l2gcv21Y
        ndtiE59hzVMl7clDTE3h7HOIshqGimJFRN/N7ZME9N0HKRaVLWbwhy2iY8XX4eYq
        ldeFMROO4EhZBoGmY9s+syaiJopUYAk3dQrzPzcCgYB8cKv6aqNfM2CITdV54jFH
        I/6VCKTv8OIxVIS7m19UILD4mINBk2DKrBLuWV7O9fLlgjKy8k59cnsQj3pDmir7
        R2P3u4IgFyX5Lo9lPmrCLhVsWXjjKyMnna4wUcqooAPZcSih3ikCZtWZSLbJzdnn
        OFl6FvUsujYAAcdMhk/0tQKBgDz5hiaJx9xMr23vbkbfqxgoz0k3LqW6PyxJb8Vn
        BBVF630n1x0driK3Dl/bH7TYWq8zEkMa3Pq16jG7T8dd0coJOQEiAG9dar3bbTPQ
        g1EpXJBsKQGd86YXx8rCZzarzWy++GWIthjauuQmbO5knlvjVSlYUZen6i2ScmPl
        qH39AoGBAKYQQYlCcaH4Lw5Wo9TuTcGAYtrDQ0cyTUeppy/RBIRD4+FqDRLyAg76
        djNczCRIU0WZUiXj7lZ4Dy3oUFnYPA56yzPlClhtkHr/X+vyI7jiJ/Y/NpPoXOBm
        5wG9SIIjazjeaE2IiWCKiPe3BWI/GHm4zfURckyaHlzOUiF3DRTX
        -----END RSA PRIVATE KEY-----
        
