#!/bin/bash

MachineTypes=$(gcloud compute machine-types list --filter="zone: us-east1-b" --format=value"(NAME,CPUS,MEMORY_GB)")

ClusterJson=$(yq -jP r - <  cluster.yaml)

PartitionNames=$(echo "$ClusterJson" | jq -r '.[].partitions|keys|.[]')
for PartitionName in ${PartitionNames}
do
	PartitionJson=$(echo "$ClusterJson" | jq -r '.[].partitions["'${PartitionName}'"]')
	NodeJson=$(echo "$PartitionJson" | jq -r '.nodes')

	PartitionSpec=()

#	Name Nodes Default State MaxTime LLN

	PartitionSpec+=( PartitionName=$PartitionName )

	Nodes=$(echo $NodeJson | jq -r '.name')
	PartitionSpec+=( Nodes="$Nodes" )
	
	Default=$(echo "$PartitionJson" | jq -r '.Default')
	if (! echo "$Default" | grep -q null)
	then
		PartitionSpec+=( Default=$Default )
	fi

	State=$(echo "$PartitionJson" | jq -r '.State')
	if [ "$State" != null ]
	then
		PartitionSpec+=( State="$State" )
	fi

	LLN=$(echo "$PartitionJson" | jq -r '.LLN')
	if [ "$LLN" != null ]
	then
		PartitionSpec+=( LLN="$LLN" )
	fi

	echo "${PartitionSpec[@]}"

	NodeSpec=()

	NodeSpec+=( NodeName=$(echo "$NodeJson" | jq -r '.name') )

	State=$(echo "$NodeJson" | jq -r '.State')
	if [ "$State" != null ]
	then
		NodeSpec+=( State=$State )
	fi

	MachineType=$(echo "$NodeJson" | jq -r '.MachineType')
	if [ "$MachineType" != null ]
	then
		NodeSpec+=( CPUs=$(echo "$MachineTypes" | grep -P "^${MachineType}\s" | awk '{print $2}') )
		NodeSpec+=( RealMemory=$((echo scale=0; (echo "$MachineTypes" | grep -P "^${MachineType}\s" | awk '{print $3}' ; echo '* 1024 / 1') | paste -sd" \n") | bc ) )
	fi

	echo "${NodeSpec[@]}"
	echo
done