#!/bin/bash

SlurmDir=/share/apps/slurm
ClusterYamlFile=${SlurmDir}/scripts/cluster.yaml
SlurmDbdTemplateFile=${SlurmDir}/scripts/slurmdbd.conf.template

SlurmDbdJson=$(yq -jP r - < "$ClusterYamlFile" | jq '.[].SlurmDbd')
(echo "$SlurmDbdJson" | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' ; echo "envsubst < ${SlurmDbdTemplateFile}") | bash

